Operaciones vectoriales con arrays o arreglos

    *Numpy is a python library, is used for working with arrays and is short for numerical python
    **Numpy is up to 50x faster than traditional python lists.
    ***The array object in Numpy is called ndarray.
    ****Numpy is written in C or C++ and partially written in Python.

Pasos previos. Importar numpy as pd

In [2]:
import numpy as np #El alías np es el de uso mas extenso y genealizado en la comunidad de DS

Opcional. Verificar la versión de Numpy.

In [6]:
print("la versión de Numpy utilizadas es la: ",np.__version__)

la versión de Numpy utilizadas es la:  1.21.5


1. Create a NunmPy ndarray object.
    array() function

In [9]:
#Crear un array desde una lista
arreglo = np.array([1,2,3,4,5])
print(arreglo)
print(type(arreglo))

[1 2 3 4 5]
<class 'numpy.ndarray'>


In [10]:
#Crear un array desde una tupla

tupla = np.array((6,7,8,9,0))
print(tupla)
print(type(tupla))

[6 7 8 9 0]
<class 'numpy.ndarray'>


Dimension in arrays.

    *A dimension in arrays is a level of array depth (nested arrays:arrays with arrays in theirs elements).

0-D or Scalar

*0-D Arrays or Scalars, son los arrays donde la solo hay un elemento, es decir, la posición 0

In [19]:
arreglo_D0 = np.array(42)
print(arreglo_D0)

42


1-D Arrays or Vector

*Es una array donde todos sus elementos estan todos en la fila o columna 0



In [12]:
arreglo_D1 = np.array([1,2,3,4])
print(arreglo_D1)

[1 2 3 4]


2-D Arrays or bidimensional array

*Es una array 
q que contiene mas de 1D arrays como elementos, se conoce también como matriz, normalmente suele tener forma de rectangulo

In [14]:
arreglo_D2 = np.array([[1,2,3],[4,5,6]])
print(arreglo_D2)

[[1 2 3]
 [4 5 6]]


3-D Arrays or Tensor

    *An array that has 2-D arrays (matrices) as its elements.

In [17]:
arreglo_D3 = np.array([arreglo_D2,arreglo_D2])
print(arreglo_D3)

[[[1 2 3]
  [4 5 6]]

 [[1 2 3]
  [4 5 6]]]


Check numbers of dimensions?

    *ndim attribute returns the number of dimensions

In [24]:
print("El array arreglo_D0 tiene un total de {} dimensiones".format(arreglo_D0.ndim))
print("El array arreglo_D1 tiene un total de {} dimensiones".format(arreglo_D1.ndim))
print("El array arreglo_D2 tiene un total de {} dimensiones".format(arreglo_D2.ndim))
print("El array arreglo_D3 tiene un total de {} dimensiones".format(arreglo_D3.ndim))

El array arreglo_D0 tiene un total de 0 dimensiones
El array arreglo_D1 tiene un total de 1 dimensiones
El array arreglo_D2 tiene un total de 2 dimensiones
El array arreglo_D3 tiene un total de 3 dimensiones


Higher dimensional Arrays

    *An array can have any number of dimensions.
    when the array is created, you can define the number of dimensions using the ndmin argument.

In [27]:
arreglo_D5 = np.array([1,2,3,4,5], ndmin = 5)
print(arreglo_D5)
print("El array arreglo_D5 tien un total de {} dimensiones".format(arreglo_D5.ndim))

[[[[[1 2 3 4 5]]]]]
El array arreglo_D5 tien un total de 5 dimensiones


Data Types in NumPy format

    i = integer
    b = boolean
    u = unsigned integer
    f = float
    c = complex float
    m = timedelta
    M = datetime
    O = object
    S = string


NumPy Array Indexing

    Examples:
            arr = np.array([1, 2, 3, 4])
            Get the first element from the previous array.
            Get the second element from the previous array.
            Get third and fourth elements from the previous array and add them.


In [33]:
arregloIndexado = np.array([1,2,3,4])

print("El primer elemento del arregloIndexado es {}.".format(arregloIndexado[0]))
print("El segundo elemento del arregloIndexado es {}.".format(arregloIndexado[1]))
print("El tercer y cuarto elemento de arregloIndexado son {} y {}, su adición da como resultado {}.".format(arregloIndexado[2],arregloIndexado[3],arregloIndexado[2]+arregloIndexado[3]))

El primer elemento del arregloIndexado es 1.
El segundo elemento del arregloIndexado es 2.
El tercer y cuarto elemento de arregloIndexado son 3 y 4, su adición da como resultado 7.


Acces 2-D Arrays

    We can use a comma separated integers representing the dimensions and the index of the element.

    Example:
            arregloEjemplo2 = np.array([[1,2,3,4,5], [6,7,8,9,10]])
            Access the element on the firts row, second column
            Access the element on the 2nd row, 5th column.

In [37]:
arregloEjemplo2 = np.array([[1,2,3,4,5],[6,7,8,9,10]])

print(arregloEjemplo2)

print("El elemento ubicado en la fila (dimensión) 1, columa 2 es {}.".format(arregloEjemplo2[0,1]))
print("El elemento ubicado en la fila (dimensión) 2, columa 5 es {}.".format(arregloEjemplo2[1,4]))

[[ 1  2  3  4  5]
 [ 6  7  8  9 10]]
El elemento ubicado en la fila (dimensión) 1, columa 2 es 2.
El elemento ubicado en la fila (dimensión) 2, columa 5 es 10.


Access 3-D Arrays

We can use a comma separated integers representing the dimensions and the index of the element.

    Example:
            arregloEjemplo3 = np.array([[[1,2,3],[4,5,6]],[[7,8,9],[10,11,12]]])
            Access the third element of the second array of the first array

In [41]:
arregloEjemplo3 = np.array([[[1,2,3],[4,5,6]],[[7,8,9],[10,11,12]]])

print(arregloEjemplo3)
print("El 3er elemento contenido en el segundo array que a la vez se encuentra en el primer array es {}.".format(arregloEjemplo3[0,1,2]))

[[[ 1  2  3]
  [ 4  5  6]]

 [[ 7  8  9]
  [10 11 12]]]
El 3er elemento contenido en el segundo array que a la vez se encuentra en el primer array es 6.


Explicación:

        la matriz tiene 2 arrays de 2D siendo el primer array [[1,2,3],[4,5,6]] y el segundo array [[7,8,9],[10,11,12]]
        El segundo array que se encuentra dentro del 1er array sería [4,5,6]
        El tercer elemento del segundo array sería 6

Negative Indexing

    Acceder a un array desde su elemento final

In [45]:
"""Print the last element of the 2nd dimension"""
arregloNegativo = np.array([[1,2,3,4,5],[6,7,8,9,10]])
print(arregloNegativo)
print("The last element of the 2nd dim is {}.".format(arregloNegativo[1,-1]))

[[ 1  2  3  4  5]
 [ 6  7  8  9 10]]
The last element of the 2nd dim is 10.


paso 1. Importar numpy as pd